config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks/new', to: 'tasks#new'
  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: :task
  # get '/tasks/new', to: 'tasks#new', as: 'new_task'

  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  # patch '/tasks/:id', to: 'tasks#update'
  patch '/tasks/:id', to: 'tasks#update', as: 'update_task'
  delete '/tasks/:id', to: 'tasks#destroy', as: 'delete_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
      @tasks = Task.all
    end
  
    def show
      @task = Task.find(params[:id])
    end
  
    def new
      @task = Task.new
    end
  
    def create
      @task = Task.new(task_params)
      if @task.save
        redirect_to @task
      else
        render 'new'
      end
    end
  
    def edit
      @task = Task.find(params[:id])
    end
  
    def update
      @task = Task.find(params[:id])
      if @task.update(task_params)
        redirect_to @task
      else
        render 'edit'
      end
    end

  
    def destroy
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path, status: :see_other
    end
  
    private
  
    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit task </h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %> 
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks </h1>

<% @tasks.each do |task| %>
  <div class="task">
    <label>
      <%= check_box_tag "completed_task_ids[]", task.id, false %>
      <%= link_to task.title, task_path(task)  %>
      <%= link_to "X",
  task_path(task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %></label>
   
  </div>
<% end %>
<%= link_to "Add to new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>My tasks </h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p class="groove" ><%= @task.details %></p>
<%# <p> <%= @task.completed</p> %>
<%# <i class="fa-regular fa-square"></i>
<%= form_with  model: @task do |f| %>
<%# <%= f.check_box :completed, {}, 'Task is completed', 'Task is not completed'  %>
<%# <% end%> 

<div><% if @task.completed %>
  <i class="fas fa-check-square"> </i> Task is completed</label><!-- Checked square icon -->
<% else %>
  <i class="far fa-square"></i> Task is not completed </label> <!-- Unchecked square icon -->
<% end %></div>
 

<div> 
<%= link_to "Edit", edit_task_path(@task) %>
</div>

<div>
<%= link_to "Back to list", tasks_path %>
</div>

<div><%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%></div>